export const CITY_LOCALITIES: Record<string, string[]> = {
  'Hyderabad': [
    'Bachupally',
    'Gachibowli',
    'Kondapur',
    'Miyapur',
    'Kukatpally',
    'Nallakunta',
    'Jubilee Hills',
    'Banjara Hills',
    'Madhapur',
    'Hitec City',
    'Begumpet',
    'Secunderabad',
    'Uppal',
    'LB Nagar',
    'Himayatnagar',
    'Manikonda',
    'Ameerpet',
    'Other (please specify)'
  ],
  'Bangalore': [
    'Indiranagar',
    'Koramangala',
    'Whitefield',
    'HSR Layout',
    'Jayanagar',
    'JP Nagar',
    'Marathahalli',
    'Electronic City',
    'Yelahanka',
    'Rajajinagar',
    'Banashankari',
    'Bellandur',
    'Malleshwaram',
    'Sarjapur Road',
    'Hebbal',
    'BTM Layout',
    'Other (please specify)'
  ],
  'Delhi NCR': [
    'Gurgaon - DLF Phase 1-5',
    'Gurgaon - Cyber City / Golf Course Road',
    'Gurgaon - Sohna Road & Extension',
    'Noida - Sector 18 & Central Noida',
    'Noida - Sector 62 & Indirapuram',
    'Noida - Sector 137 & Express Way',
    'Greater Noida',
    'South Delhi - Vasant Kunj & Saket',
    'South Delhi - Hauz Khas & South Ext',
    'West Delhi - Dwarka & Janakpuri',
    'North Delhi - Rohini & Pitampura',
    'Central Delhi - CP & Karol Bagh',
    'East Delhi - Mayur Vihar & Laxmi Nagar',
    'Faridabad',
    'Ghaziabad - Vaishali & Vasundhara',
    'Other (please specify)'
  ],
  'Ahmedabad': [
    'SG Highway',
    'Satellite',
    'Bodakdev',
    'Prahlad Nagar',
    'Vastrapur',
    'Navrangpura',
    'Paldi',
    'Bopal',
    'Thaltej',
    'Maninagar',
    'Chandkheda',
    'Science City',
    'Gota',
    'Motera',
    'Ambawadi',
    'Other (please specify)'
  ],
  'Pune': [
    'Kothrud',
    'Baner',
    'Viman Nagar',
    'Koregaon Park',
    'Aundh',
    'Hinjewadi',
    'Wakad',
    'Pimple Saudagar',
    'Kalyani Nagar',
    'Hadapsar',
    'Magarpatta',
    'Kharadi',
    'Bavdhan',
    'Pashan',
    'Shivajinagar',
    'Other (please specify)'
  ]
};
